---

# file: playbooks/vars/os/distribution/MacOSX.yml

#
# Base
#
conf_hold_packages:
    - mod-pagespeed-stable
conf_unwanted_packages:
    # - chef
conf_base_packages:
    - zsh
    - vim
    # - screen
    - golang
    - tmux
    - tmate
    - mosh
    - tree
    - unzip
    - whois
    - htop
    - ccze
    - subversion
    - nmap
    - wget
    - curl
    - links
    - lynx
    - traceroute
    - make
    - git
    - convmv
