---

# file: playbooks/roles/common/tasks/fail2ban.yml

- name: Ensure iptables is installed
  package: name=iptables state=installed
  tags: [ firewall ]

- name: Flush iptables the first time playbook runs
  command: >
    iptables -F
    creates=/etc/firewall.bash
  tags: [ firewall ]

- name: Copy firewall script into place
  template:
    src: etc/firewall.bash.j2
    dest: /etc/firewall.bash
    owner: root
    group: root
    mode: 0744
  notify: restart firewall
  tags: [ firewall ]

- name: Copy firewall init script into place
  template:
    src: etc/init.d/firewall.j2
    dest: /etc/init.d/firewall
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"
  tags: [ firewall ]

- name: Copy firewall systemd unit file into place (for systemd systems)
  template:
    src: etc/systemd/system/firewall.service.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"
  tags: [ firewall ]

- name: Ensure the firewall is enabled and will start on boot
  service: name=firewall state=started enabled=yes
  tags: [ firewall ]

# - include: disable-other-firewalls.yml
#   when: conf_firewall_disable_firewalld or conf_firewall_disable_ufw
#   tags: [ firewall ]

- name: Check if firewalld package is installed (on RHEL)
  shell: yum list installed firewalld
  args:
    warn: no
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == "RedHat" and conf_firewall_disable_firewalld
  tags: [ firewall ]

- name: Disable the firewalld service (on RHEL, if configured)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat" and conf_firewall_disable_firewalld and firewalld_installed.rc == 0
  tags: [ firewall ]

- name: Check if ufw package is installed (on Ubuntu)
  shell: service ufw status
  args:
    warn: no
  register: ufw_installed
  ignore_errors: true
  changed_when: false
  when: ansible_distribution == "Ubuntu" and conf_firewall_disable_ufw
  tags: [ firewall ]

- name: Disable the ufw firewall (on Ubuntu, if configured)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_distribution == "Ubuntu" and conf_firewall_disable_ufw and ufw_installed.rc == 0
  tags: [ firewall ]

- name: Check if ufw package is installed (on Archlinux)
  command: pacman -Q ufw
  args:
    warn: no
  register: ufw_installed
  ignore_errors: true
  changed_when: false
  when: ansible_distribution == "Archlinux" and conf_firewall_disable_ufw
  tags: [ firewall ]

- name: Disable the ufw firewall (on Archlinux, if configured)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_distribution == "Archlinux" and conf_firewall_disable_ufw and ufw_installed.rc == 0
  tags: [ firewall ]
