---

# file: playbooks/roles/common/tasks/lvm.yml

- name: be sure base lvm is installed (Debian family)
  apt: pkg={{ item }} state=installed
  with_items:
    - lvm2
    - xfsprogs
  when: ansible_os_family == "Debian" and conf_lvm_enable == true
  tags: [ lvm, xfs, update ]

#
# Create PVs and VGs
#
- name: create VGs on PVs
  lvg: vg={{ item.0.name }} pvs={{ item.1 }}
  with_subelements:
    - "{{ conf_lvm_vgs }}"
    - pvs
  when: conf_lvm_enable is defined and conf_lvm_enable == true and conf_lvm_pvcreate == true
  tags: [ lvm ]

#
# Create LVs
#
- name: create LVs
  lvol: vg={{ item.vg }} lv={{ item.name }} size={{ item.size }} state={{ item.state }} force=yes
  with_items:
    - "{{ conf_lvm_lvs }}"
  when: conf_lvm_enable is defined and conf_lvm_enable == true and conf_lvm_pvcreate == true
  tags: [ lvm ]

- name: create filesystems
  filesystem: fstype={{ item.fstype }} dev=/dev/{{ item.vg }}/{{ item.name }} resizefs=no
  with_items:
    - "{{ conf_lvm_lvs }}"
  when: conf_lvm_enable is defined and conf_lvm_enable == true and conf_lvm_pvcreate == true
  tags: [ lvm, xfs, swap ]

- name: edit fstab
  mount: name={{ item.mountpoint }} src=/dev/mapper/{{ item.vg }}-{{ item.name }} fstype={{ item.fstype }} dump={{ item.dump }} passno={{ item.passno }} state={{ item.state }}
  with_items:
    - "{{ conf_lvm_lvs }}"
  when: conf_lvm_enable is defined and conf_lvm_enable == true
  tags: [ lvm, fstab, swap ]

- name: mount filesystems (not swap)
  mount: name={{ item.mountpoint }} src=/dev/mapper/{{ item.vg }}-{{ item.name }} fstype={{ item.fstype }} dump={{ item.dump }} passno={{ item.passno }} state=mounted
  with_items:
    - "{{ conf_lvm_lvs }}"
  when: conf_lvm_enable is defined and conf_lvm_enable == true and item.fstype != "swap"
  tags: [ lvm, fstab ]

# - name: swapon
#   command: "sudo swapon /dev/mapper/{{ item.vg }}-{{ item.name }}"
#   with_items:
#     - "{{ conf_lvm_lvs }}"
#   ignore_errors: yes
#   when: conf_lvm_enable is defined and conf_lvm_enable == true and item.fstype == "swap"
#   tags: [ lvm, fstab, swap ]

#
# This can be only done for XFS mounted fs
#
- name: resize filesystems (not swap)
  filesystem: fstype={{ item.fstype }} dev=/dev/{{ item.vg }}/{{ item.name }} resizefs=yes
  with_items:
    - "{{ conf_lvm_lvs }}"
  when: conf_lvm_enable is defined and conf_lvm_enable == true and item.fstype != "swap"
  tags: [ lvm, xfs ]
