---

# file: playbooks/vars/os/distribution/Ubuntu.yml

#
# locales
#
conf_locales_dependencies:
  - tzdata
  - locales
conf_locales_gen_file: "{{ '/var/lib/locales/supported.d/local' if ansible_distribution == 'Ubuntu' else '/etc/locale.gen' }}"

#
# Base
#
conf_root_shell: "/bin/bash"
conf_etc_path: "/etc"
conf_local_etc_path: "/etc"
conf_lib_path: "/usr/lib"
conf_bin_path: "/usr/bin"
conf_zsh_path: "/bin/zsh"
conf_bash_path: "/bin/bash"
conf_root_group: "root"
conf_www_group: "www-data"
conf_sudo_nopasswd_group: "admin"
conf_hold_packages:
    - mod-pagespeed-stable
    - ansible
conf_unwanted_packages:
    - chef
    - chef-zero
    - puppet
    - puppet-common
    - ntfs-3g
    - ufw
    - libpolkit-backend-1-0
    - libpolkit-agent-1-0
    - xserver-xorg-core
    - libdrm-nouveau2
    - libxcomposite1
    - erubis
    - libgl1-mesa-dri
    - libgl1-mesa-glx
    - libglapi-mesa
    - libllvm3.4
    - libtxc-dxtn-s2tc0
    - libx11-xcb1
    - libxcb-dri2-0
    - libxcb-dri3-0
    - libxcb-glx0
    - libxcb-present0
    - libxcb-sync1
    - libxdamage1
    - libxfixes3
    - libxshmfence1
    - libxxf86vm1
    - byobu
    - nano
    - manpages-dev
conf_base_packages:
    - xfsprogs
    - deborphan
    - aptitude
    - apt-transport-https
    - apt-dater-host
    - zsh
    - bsd-mailx
    - vim
    - uptimed
    - screen
    - tmux
    - mosh
    - finger
    - tree
    - telnet
    - unzip
    - zip
    - whois
    - htop
    - ccze
    - subversion
    - nmap
    - dnsutils
    - wget
    - curl
    - links
    - lynx
    - traceroute
    - acl
    - make
    - golang-1.8-go
    - "{{ var_package_git }}"
    - convmv
    - tig
conf_php_cli: "/usr/bin/php"
conf_php_extension_dir: "/usr/lib/php/20131226"
conf_php_ioncube_loader_so: "ioncube_loader_lin_5.6.so"
conf_web_cron: "/etc/cron.d/wp-cron"
conf_ssh_service: ssh

#
# Supervisor
#
conf_supervisor_bin_path: /usr/local/bin/supervisord

#
# MySQL/Percona
#
conf_mysql_conf: "/etc/mysql/my.cnf"
conf_mysql_basedir: "/usr"
conf_mysql_datadir: "/var/lib/mysql"
conf_mysql_lc_messages_dir: "/usr/share/mysql"
conf_mysql_socket: "/var/run/mysqld/mysqld.sock"

#
# HAProxy
#
conf_haproxy_socket_path: "/run/haproxy"
conf_haproxy_errors_path: "/etc/haproxy/errors"

#
# Etckeeper
#
conf_etckeeper_lowlevel_package_manager: "dpkg"
conf_etckeeper_highlevel_package_manager: "apt"

#
# nginx
#
conf_nginx_conf_path: /etc/nginx/conf.d
conf_nginx_conf_file_path: /etc/nginx/nginx.conf
conf_nginx_mime_file_path: /etc/nginx/mime.types
conf_nginx_pidfile: /run/nginx.pid
conf_nginx_vhost_path: /etc/nginx/sites-enabled
conf_nginx_default_vhost_path: /etc/nginx/sites-enabled/default
__conf_nginx_user: "www-data"

#
# redis
#
__conf_redis_package: redis-server
conf_redis_daemon: redis-server
conf_redis_conf_path: /etc/redis/redis.conf

#
# etcd
#
conf_etcd_config_only: False
conf_etcd_install_dependencies:
  - rsync
  - openssh-server
