---

# file: playbooks/roles/db/defaults/main.yml

#
# MySQL
#
conf_mysql_flavour_debian_family: percona-xtradb-cluster
conf_mysql_version_debian_family: 5.6
conf_mysql_expire_logs_days: 3
conf_mysql_thread_stack: 576K
conf_mysql_key_buffer: 16M

#
# galeranotify
#
conf_galera_notify_enable: false
conf_galera_notify_slack_enable: false

#
# Cassandra
#
conf_cassandra_enable: false
conf_cassandra_gpg_keyserver: pool.sks-keyservers.net
conf_cassandra_gpg_key_id: A278B781FE4B2BDA
conf_cassandra_series_version: 311x
conf_cassandra_cluster_name: "cassandra_cluster"
# conf_cassandra_listen_address: 127.0.0.1
# conf_cassandra_listen_interface: eth0
conf_cassandra_start_rpc: false
conf_cassandra_rpc_address: 0.0.0.0
conf_cassandra_broadcast_rpc_address: 127.0.0.1
conf_cassandra_rpc_port: 9160
conf_cassandra_endpoint_snitch: SimpleSnitch
conf_cassandra_rackdc_dc: dc1
conf_cassandra_rackdc_rack: rack1
conf_cassandra_topology: |
  # Cassandra Node IP=Data Center:Rack
  192.168.1.100=DC1:RAC1
  192.168.2.200=DC2:RAC2

  10.0.0.10=DC1:RAC1
  10.0.0.11=DC1:RAC1
  10.0.0.12=DC1:RAC2

  10.20.114.10=DC2:RAC1
  10.20.114.11=DC2:RAC1

  10.21.119.13=DC3:RAC1
  10.21.119.10=DC3:RAC1

  10.0.0.13=DC1:RAC2
  10.21.119.14=DC3:RAC2
  10.20.114.15=DC2:RAC2

  # default for unknown nodes
  default=DC1:r1

  # Native IPv6 is supported, however you must escape the colon in the IPv6 Address
  # Also be sure to comment out JVM_OPTS="$JVM_OPTS -Djava.net.preferIPv4Stack=true"
  # in cassandra-env.sh
  fe80\:0\:0\:0\:202\:b3ff\:fe1e\:8329=DC1:RAC3
