---

# file: playbooks/roles/web/tasks/htpasswd.yml

#
# htpasswd
#
- name: be sure python-passlib package is installed (Ubuntu)
  apt: pkg={{ item }} state=installed
  with_items:
    - python-passlib
  when: ansible_distribution == "Ubuntu"
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: [ vhosts, htpasswd ]

# - name: /etc/htpasswd
#   file: path=/etc/htpasswd mode=750 state=directory owner=root group={{ conf_www_group }}
#   tags: [ vhosts, htpasswd ]

# - name: debug
#   debug: msg="{{ item.value.htpasswd_password }}"
#   with_dict: '{{ conf_vhosts_common }}'
#   tags: [ vhosts, htpasswd ]

- name: add htpasswd entry
  htpasswd: path=/etc/apache2/.htpasswd name={{ item.key }} password={{ item.value.htpasswd_password }} state=present owner=root group={{ conf_www_group }} mode=0640
  when:
    - item.value.htpasswd_password is defined
    - item.value.htpasswd_password != false
  with_dict: '{{ conf_vhosts_common }}'
  tags: [ vhosts, htpasswd ]

- name: remove htpasswd entry
  htpasswd: path=/etc/apache2/.htpasswd name={{ item.key }} state=absent owner=root group={{ conf_www_group }} mode=0640
  when:
    - item.value.htpasswd_password is defined
    - item.value.htpasswd_password == false
  with_dict: '{{ conf_vhosts_common }}'
  tags: [ vhosts, htpasswd ]
