---

# file: playbooks/roles/web/tasks/php.yml

#
# PPA migration: https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php
#

- name: remove osbolete 5.6 PPA (Ubuntu)
  file: name=/etc/apt/sources.list.d/{{ item }} state=absent
  with_items:
    - "ppa_ondrej_php5_5_6_trusty.list"
  when: ansible_distribution == "Ubuntu"
  tags: [ php, update ]

- name: PHP PPA (Ubuntu)
  apt_repository: repo='ppa:ondrej/php' update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version != "12.04"
  ignore_errors: yes
  tags: [ php, update ]

#
# TODO: Add Debian PPA, https://packages.sury.org/php/
#

- name: be sure web packages packages are installed (RedHat family)
  yum: pkg={{ item }} state=latest
  with_items:
    - httpd
  when: ansible_os_family == "RedHat"
  tags: [ php, apache2 ]

- name: be sure web packages packages are installed (Debian family)
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - apache2
    - libapache2-mod-php{{ conf_php_version_debian_family }}
    - libapache2-mod-rpaf
    - apachetop
    - php{{ conf_php_version_debian_family }}
    - php{{ conf_php_version_debian_family }}-cli
    - php{{ conf_php_version_debian_family }}-gd
    - php{{ conf_php_version_debian_family }}-json
    - php{{ conf_php_version_debian_family }}-mysql
    - php{{ conf_php_version_debian_family }}-tidy
    - php{{ conf_php_version_debian_family }}-curl
    - php{{ conf_php_version_debian_family }}-gd
    - php{{ conf_php_version_debian_family }}-imagick
    - php{{ conf_php_version_debian_family }}-imap
    - php{{ conf_php_version_debian_family }}-intl
    - php{{ conf_php_version_debian_family }}-ldap
    - php{{ conf_php_version_debian_family }}-mcrypt
    - php{{ conf_php_version_debian_family }}-gettext
    - php{{ conf_php_version_debian_family }}-xml
    - php{{ conf_php_version_debian_family }}-mbstring
    - php{{ conf_php_version_debian_family }}-soap
    - php{{ conf_php_version_debian_family }}-zip
    - php{{ conf_php_version_debian_family }}-sqlite3
    # - php5-common
    - php-memcached
    - php-db
    - php-mdb2
    - php-pear
    - imagemagick
    - gifsicle
    - optipng
    - libjpeg-progs
    - libimage-exiftool-perl
    # - varnish
    - memcached
  when: ansible_os_family == "Debian"
  ignore_errors: yes
  tags: [ php, apache2 ]

- name: update-alternatives (Debian family)
  alternatives: name={{ item }} path=/usr/bin/{{ item }}{{ conf_php_version_debian_family }}
  with_items:
    - php
    - phar
    - phar.phar
  when: ansible_os_family == "Debian"
  ignore_errors: yes
  tags: [ php, apache2 ]

- name: be sure web packages packages are installed (FreeBSD)
  pkgng: name={{item}} state=present
  with_items:
    - php6-5.6.1
    - php6-json-5.6.1
    - php6-phar-5.6.1
    - php6-filter-5.6.1
    - php6-hash-5.6.1
    - php6-ctype-5.6.1
    - php6-openssl-5.6.1
  when: ansible_distribution == "FreeBSD"
  tags: [ php ]

- name: deploy php.ini (Debian family)
  template: src=etc/php/{{ conf_php_version_debian_family }}/{{ item }}/php.ini.j2 dest={{ conf_local_etc_path }}/php/{{ conf_php_version_debian_family }}/{{ item }}/php.ini owner=root group={{ conf_root_group }} mode=0644
  with_items:
    - apache2
    - cli
  when: ansible_os_family == "Debian"
  notify: handle_restart_apache2
  tags: [ php, php-conf ]

- name: config PHP date.timezone (Debian family)
  action: ini_file dest=/etc/php/{{ conf_php_version_debian_family }}/{{ item }}/php.ini section=Date option=date.timezone value='"{{ conf_timezoneÂ }}"' mode=0644
  with_items:
    - "apache2"
    - "cli"
  notify: handle_restart_apache2
  when: ansible_os_family == "Debian"
  tags: [ php, php-conf ]

- name: config PHP error_log (Debian family)
  action: ini_file dest=/etc/php/{{ conf_php_version_debian_family }}/{{ item }}/php.ini section=PHP option=error_log value='/var/log/apache2/php_error.log' mode=0644
  with_items:
    - "apache2"
  notify: handle_restart_apache2
  when: ansible_os_family == "Debian"
  tags: [ php, php-conf ]

- name: config PHP display_errors off  (Debian family, production)
  action: ini_file dest=/etc/php/{{ conf_php_version_debian_family }}/{{ item }}/php.ini section=PHP option=display_errors value=Off mode=0644
  with_items:
    - "apache2"
  notify: handle_restart_apache2
  when: conf_env == "production" and ansible_os_family == "Debian"
  tags: [ php, php-conf ]
