---

# file: playbooks/roles/lb/defaults/main.yml

#
# lbtier
#
conf_lbtier_enable: false

#
# etcd
#

# Installation Variables
conf_etcd_config_only: False
conf_etcd_daemon: "systemctl"

# Download Variables
conf_etcd_version: v3.2.9
conf_etcd_checksum: 1e962459cb649363215eb022eb7ea8857ea95dce836eb9ff3b3dc54c851b4cb1.
conf_etcd_platform: linux
conf_etcd_arch: amd64
conf_etcd_release: "etcd-{{ conf_etcd_version }}-{{ conf_etcd_platform }}-{{ conf_etcd_arch }}"
conf_etcd_download_url: "https://github.com/coreos/etcd/releases/download/{{ conf_etcd_version }}/{{ conf_etcd_release }}.tar.gz"
conf_etcd_download_dir: /usr/local/src
conf_etcd_download_filename: "{{ conf_etcd_release }}.tar.gz"

# Runtime Variables
conf_etcd_dir: /usr/local/sbin
conf_etcd_data_dir: /var/cache/etcd/state
conf_etcd_cmd: "{{ conf_etcd_dir }}/etcd"
conf_etcd_user: root  # The user only applies to EL distros

# Networking Variables
conf_etcd_interface: lo
conf_etcd_client_interface: "{{ conf_etcd_interface }}"
conf_etcd_peer_interface: "{{ conf_etcd_interface }}"
conf_etcd_client_port: 2379
conf_etcd_peer_port: 2380
conf_etcd_peers_group: etcd
conf_etcd_url_scheme: http
conf_etcd_client_url_scheme: "{{ conf_etcd_url_scheme }}"
conf_etcd_peer_url_scheme: "{{ conf_etcd_url_scheme }}"

conf_etcd_initial_cluster_state: new
conf_etcd_initial_cluster_token: etcd-cluster-1

conf_etcd_initial_advertise_peer_urls: "{{ conf_etcd_peer_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + conf_etcd_peer_interface]['ipv4']['address'] }}:{{ conf_etcd_peer_port }}"
conf_etcd_listen_peer_urls: "{{ conf_etcd_peer_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + conf_etcd_peer_interface]['ipv4']['address'] }}:{{ conf_etcd_peer_port }}"
conf_etcd_advertise_client_urls: "{{ conf_etcd_client_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + conf_etcd_client_interface]['ipv4']['address'] }}:{{ conf_etcd_client_port }}"
conf_etcd_listen_client_urls: "{{ conf_etcd_client_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_' + conf_etcd_client_interface]['ipv4']['address'] }}:{{ conf_etcd_client_port }}"

conf_etcd_client_cert_file: ~
conf_etcd_client_key_file: ~
conf_etcd_client_cert_auth: False
conf_etcd_client_trusted_ca_file: ~

conf_etcd_peer_cert_file: ~
conf_etcd_peer_key_file: ~
conf_etcd_peer_client_cert_auth: False
conf_etcd_peer_trusted_ca_file: ~

conf_etcd_discovery: ~
conf_etcd_discovery_srv: ~
