---

# file: playbooks/roles/common/defaults/main.yml

#
# Custom playbook
#
conf_custom_playbook_enable: false
conf_custom_playbook_import_tasks: []

#
# mount
#
conf_mount_enable: false
conf_mount:
  - path: ''
    dump: 0
    fstab: '/etc/fstasb'
    fstype: ''
    opts: ''
    passno: 0
    src: ''
    state:

#
# locales
#
conf_locales_present:
  - en_US.UTF-8
conf_locales_language_packs_present:
  - language-pack-en
  - language-pack-en-base
conf_locales_absent: []
conf_locales_language_packs_absent: []
conf_locales_default:
  lang: en_US.UTF-8

#
# Sysctl
#
conf_sysctl_enable: false
conf_sysctl_dict:
  - { k: net.ipv4.ip_nonlocal_bind       , v: 1 }
  # - { k: net.ipv4.tcp_tw_recycle       , v: 1 }
  # - { k: net.ipv4.tcp_tw_reuse         , v: 1 }
  # - { k: net.ipv4.tcp_fin_timeout      , v: 30 }
  # - { k: net.ipv4.tcp_keepalive_time   , v: 10 }
  # - { k: net.ipv4.tcp_keepalive_probes , v: 2 }
  # - { k: net.ipv4.tcp_keepalive_intvl  , v: 3 }
  # - { k: net.ipv4.ip_local_port_range  , v: "10240 65535" }
  # - { k: net.core.somaxconn            , v: 65535 }
  # - { k: net.ipv4.tcp_max_syn_backlog  , v: 65535 }
  # - { k: net.core.netdev_max_backlog   , v: 16384 }

#
# ACL
#
conf_acl_enable: false
conf_acl: []

#
# Base
#
conf_base_packages_custom: []

#
# snmpd
#
conf_snmpd_enable: false

#
# Jailkit
#
conf_jailkit_enable: false
conf_jailkit_url: "https://olivier.sessink.nl/jailkit/jailkit-2.19.tar.bz2"

#
# NFS client
#
conf_nfs_enable: false
conf_nfs_autofs:

#
# NFS server
#
conf_nfs_server_enable: false
conf_nfs_server_rpcmountdopts: "--manage-gids"
conf_nfs_server_exports:

#
# Supervisor
#
conf_supervisor_enable: false
conf_supervisor_version: latest
conf_supervisor_started: true
conf_supervisor_enabled: true
conf_supervisor_config_path: /etc/supervisor
conf_supervisor_programs: []
  # - name: 'apache'
  #   command: apache2ctl -c "ErrorLog /dev/stdout" -DFOREGROUND
  #   state: present
  #   configuration: |
  #     autostart=true
  #     autorestart=true
  #     startretries=1
  #     startsecs=1
  #     redirect_stderr=true
  #     stderr_logfile=/var/log/apache-err.log
  #     stdout_logfile=/var/log/apache-out.log
  #     user=root
  #     killasgroup=true
  #     stopasgroup=true
conf_supervisor_nodaemon: false
conf_supervisor_log_dir: /var/log/supervisor
# conf_supervisor_user:
# conf_supervisor_password:
conf_supervisor_unix_http_server_enable: true
conf_supervisor_unix_http_server_socket_path: /var/run/supervisor.sock
conf_supervisor_inet_http_server_enable: false
conf_supervisor_inet_http_server_port: '*:9001'

#
# Docker
#
conf_docker_enable: false

#
# redis
#
# conf_redis_enablerepo: epel
conf_redis_enable: false
conf_redis_port: 6379
conf_redis_bind_interface: 127.0.0.1
conf_redis_unixsocket: ''
conf_redis_timeout: 300
conf_redis_loglevel: "notice"
conf_redis_logfile: /var/log/redis/redis-server.log
conf_redis_databases: 16
# Set to an empty set to disable persistence (saving the DB to disk).
conf_redis_save:
  - 900 1
  - 300 10
  - 60 10000
conf_redis_rdbcompression: "yes"
conf_redis_dbfilename: dump.rdb
conf_redis_dbdir: /var/lib/redis
conf_redis_maxmemory: 0
conf_redis_maxmemory_policy: "noeviction"
conf_redis_maxmemory_samples: 5
conf_redis_appendonly: "no"
conf_redis_appendfsync: "everysec"
# Add extra include files for local configuration/overrides.
conf_redis_includes: []
# Require authentication to Redis with a password.
conf_redis_requirepass: ""
# Disable certain Redis commands for security reasons.
conf_redis_disabled_commands: []
#  - FLUSHDB
#  - FLUSHALL
#  - KEYS
#  - PEXPIRE
#  - DEL
#  - CONFIG
#  - SHUTDOWN
#  - BGREWRITEAOF
#  - BGSAVE
#  - SAVE
#  - SPOP
#  - SREM
#  - RENAME
#  - DEBUG

#
# vsftpd
#
conf_vsftpd_enable: false
conf_vsftpd_anonymous_enable: true
conf_vsftpd_connect_from_port_20: true
conf_vsftpd_group: root
conf_vsftpd_listen: true
conf_vsftpd_listen_ipv6: false
conf_vsftpd_local_enable: false
conf_vsftpd_local_umask: '022'
conf_vsftpd_mode: '0755'
conf_vsftpd_owner: root
conf_vsftpd_syslog_enable: true
conf_vsftpd_write_enable: true
conf_vsftpd_options:
  - key: xferlog_enable
    value: 'YES'
  - key: xferlog_file
    value: /var/log/vconf_sftp_xfer.log

#
# sftp
#
conf_sftp_home_partition: /home
conf_sftp_group_name: sftpusers
conf_sftp_directories: []
conf_sftp_allow_passwords: False
conf_sftp_enable_selinux_support: False
conf_sftp_enable_logging: False
conf_sftp_nologin_shell: /sbin/nologin

#
# Zabbix
#
conf_zabbix_version: 3.4
conf_zabbix_repo: zabbix
conf_zabbix_agent_packages:
  - zabbix-agent
  - zabbix-sender
  - zabbix-get

conf_zabbix_agent_package_state: present
conf_zabbix_agent_server:
conf_zabbix_agent_serveractive:
conf_zabbix_selinux: False

conf_zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: http://repo.zabbix.com/zabbix/{{ conf_zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: http://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present

# Zabbix API stuff
conf_zabbix_url: "http://zabbix.dj-wasabi.local"
conf_zabbix_api_user: Admin
conf_zabbix_api_pass: zabbix
conf_zabbix_api_create_hostgroup: False
conf_zabbix_api_create_hosts: False
conf_zabbix_create_hostgroup: present  # or absent
conf_zabbix_create_host: present       # or absent
conf_zabbix_host_status: enabled       # or disabled
conf_zabbix_proxy: null
conf_zabbix_inventory_mode: disabled
conf_zabbix_useuip: 1
conf_zabbix_host_groups:
  - Linux servers
conf_zabbix_link_templates:
  - Template OS Linux

conf_zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ conf_zabbix_useuip }}"
    ip: "{{ conf_zabbix_agent_ip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ conf_zabbix_agent_listenport }}"

conf_zabbix_agent_firewall_enable: False
# Zabbix configuration variables
conf_zabbix_agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
conf_zabbix_agent_logfile: /var/log/zabbix/zabbix_agentd.log
conf_zabbix_agent_logfilesize: 100
conf_zabbix_agent_debuglevel: 3
conf_zabbix_agent_sourceip:
conf_zabbix_agent_enableremotecommands: 0
conf_zabbix_agent_logremotecommands: 0
conf_zabbix_agent_listenport: 10050
conf_zabbix_agent_listeninterface:
conf_zabbix_agent_listenip:
conf_zabbix_agent_startagents: 3
conf_zabbix_agent_hostname: "{{ inventory_hostname }}"
conf_zabbix_agent_hostnameitem:
conf_zabbix_agent_hostmetadata:
conf_zabbix_agent_hostmetadataitem:
conf_zabbix_agent_refreshactivechecks: 120
conf_zabbix_agent_buffersend: 5
conf_zabbix_agent_buffersize: 100
conf_zabbix_agent_maxlinespersecond: 100
conf_zabbix_agent_allowroot: 0
conf_zabbix_agent_conf_zabbix_alias:
conf_zabbix_agent_timeout: 3
conf_zabbix_agent_include: /etc/zabbix/zabbix_agentd.d
conf_zabbix_agent_unsafeuserparameters: 0
conf_zabbix_agent_userparameter:
conf_zabbix_agent_loadmodulepath: ${libdir}/modules
conf_zabbix_agent_loadmodule:

# TLS settings
# conf_zabbix_agent_tlsconnect:
# conf_zabbix_agent_tlsaccept:
# conf_zabbix_agent_tlscafile:
# conf_zabbix_agent_tlscrlfile:
# conf_zabbix_agent_tlsservercertissuer:
# conf_zabbix_agent_tlsservercertsubject:
# conf_zabbix_agent_tlscertfile:
# conf_zabbix_agent_tlskeyfile:
# conf_zabbix_agent_tlspskidentity:
# conf_zabbix_agent_tlspskfile: ''
